server:
  port: ${FRONT_SERVICE_PORT:8081}

spring:
  application:
    name: front-service

user-service:
  url : ${USER_SERVICE_URL:http:\\localhost:8080}

management:
  server:
    port: 8071
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus