apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-service.fullname" . }}
  labels:
    app: {{ include "front-service.name" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "front-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "front-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.front_service_port }}
          volumeMounts:
            - name: {{ include "user-service.name" . }}
              mountPath: /config
          env:
            - name: USER_SERVICE_URL
              value: {{ .Values.user_service.base_url }}
            - name: FRONT_SERVICE_PORT
              value: {{ .Values.ports.front_service_port | quote }}
          {{- if .Values.probe.enabled -}}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      volumes:
        - name: {{ include "user-service.name" . }}
          configMap:
            name: {{ include "user-service.fullname" . }}-config