apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-service.fullname" . }}
  labels:
    app: {{ include "front-service.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "front-service.name" . }}
