apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  selector:
    app: kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: broker
      port: 9094
      targetPort: 9094
    - name: controller
      port: 9093
      targetPort: 9093
  clusterIP: None
