apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
data:
  application.yaml: |
{{ .Files.Get "files/user-service.yaml" | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-env
data:
  USER_SERVICE_PORT: {{ .Values.ports.user_service_port | quote }}
  DB_HOST: {{ .Values.user_service.DB_HOST | quote }}
  DB_PORT: {{ .Values.user_service.DB_PORT | quote }}
  DB_NAME: {{ .Values.user_service.DB_NAME | quote }}
