apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "user-service.name" . }}
