server:
  port: ${USER_SERVICE_PORT:8080}

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:my-shop}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml


