apiVersion: v1
kind: Secret
metadata:
  name: postgres-sc
type: Opaque
data:
  POSTGRES_DB: dGVzdC1rOHM=      # base64("test-k8s")
  POSTGRES_USER: YWRtaW4=   # base64("admin")
  POSTGRES_PASSWORD: YWRtaW4=   # base64("admin")