ports:
  front_service_port: 8081

user_service:
  base_url: http://user-service.default.svc.cluster.local:8080

replicaCount: 1

image:
  repository: front-service
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: test-k8s.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

volumeMounts:
  mountPath: /app/config
  value: file:/app/config/application.yaml

volumes:
  configMap:
    items:
      key: application.yaml  # Имя ключа в ConfigMap
      path: application.yaml # Имя файла в контейнере

resources: {}
probe:
  enabled: false
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}
